### ISSUE TITLE
tf, where is the code?

### ISSUE THREAD

**Issue by namzop** [AHiddenDonut/Hyena#1]
breuh wtf is this. ye chutiyapa karna band kar chutiye. code kaha hai? this repo is meaningless just like shadowX's whole life.

**Comment by siddhantshr** [comment]
Info section for Hyena API, website and your life

**Comment by namzop** [comment]
breuh why tf do you need this for
just write all this stuff on the website.

**Comment by siddhantshr** [comment]
._. my github is more popular also there's no need for you to visit this if you were here for the code

**Comment by namzop** [comment]
breauh why you acting weird smh

**Comment by namzop** [comment]
and i wasn't here for the code

**Comment by siddhantshr** [comment]
;-;

**Comment by ImNimboss** [comment]
coden't disappointment

**Comment by siddhantshr** [comment]
:v code will be public when Hyena stops ig

**Comment by ImNimboss** [comment]
cri ;-;
